	<link rel="icon" href="images/favicon.ico" type="image/x-icon" />
	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" type="text/css" href="css/basic.css" />
	<link rel="stylesheet" type="text/css" href="css/theme.css" /> 

 	
	
	<link rel="stylesheet" type="text/css" href="jsscripts/jQuery_Confirm/css/util.css" /> 	
	
<!--	<link href="style.css" rel="stylesheet" type="text/css" /> -->
	<script language="javascript" src="modules/script/ajax.js"></script>
	<script language="javascript" src="modules/script/validate.js"></script>
	<script language="javascript" src="modules/script/popcalendar.js"></script>
	<script language="javascript" src="modules/script/prototype.js"></script>
	<script language="javascript" src="modules/script/workloadjs.js"></script>
	
	<script src="jsscripts/jquery-3.1.0.min.js"></script>

	

	<script src="jsscripts/jQuery_Confirm/js/customDialog.js"></script>
	
	
	
	<script src="jsscripts/common.js"></script>
