	<link rel="icon" href="images/favicon.ico" type="image/x-icon" />
	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" type="text/css" href="css/basic.css" />
	<link rel="stylesheet" type="text/css" href="css/theme.css" /> 
<!--	<link href="style.css" rel="stylesheet" type="text/css" /> -->
	<script language="javascript" src="modules/script/ajax.js"></script>
	<script language="javascript" src="modules/script/validate.js"></script>
	<script language="javascript" src="modules/script/popcalendar.js"></script>
	<script language="javascript" src="modules/script/prototype.js"></script>
	<script language="javascript" src="modules/script/workloadjs.js"></script>